CREATE TABLE IF NOT EXISTS public.advertisement
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    image character varying(150) COLLATE pg_catalog."default",
    price integer NOT NULL,
    title character varying(250) COLLATE pg_catalog."default",
    user_id integer,
    description character varying(500) COLLATE pg_catalog."default",
    data bytea,
    meta_data character varying(150) COLLATE pg_catalog."default",
    size bigint NOT NULL,
    CONSTRAINT advertisement_pkey PRIMARY KEY (id),
    CONSTRAINT ukkoa63vw8qkde8s0fctnedy05f UNIQUE (image),
    CONSTRAINT fk9x0q2m7y1fbt6iynxr8pybprt FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.advertisement
    OWNER to postgres;