
CREATE TABLE IF NOT EXISTS public.comment
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at bigint NOT NULL,
    text text COLLATE pg_catalog."default",
    user_id integer,
    ad_id integer,
    CONSTRAINT comment_pkey PRIMARY KEY (id),
    CONSTRAINT fk3fwox5aex4cu4s7kymg9sswk8 FOREIGN KEY (ad_id)
        REFERENCES public.advertisement (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkqm52p1v3o13hy268he0wcngr5 FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.comment
    OWNER to postgres;